ARG FROM_BASE_IMAGE
FROM ${FROM_BASE_IMAGE}
# WORKDIR /opt
# RUN rm -rf NeMo \
#     && git clone \
#     -b r1.19.1 \
#     https://github.com/NVIDIA/NeMo.git

# RUN rm -rf NeMo-Megatron-Launcher \
#     && git clone \
#     -b 23.04.1 \
#     https://github.com/NVIDIA/NeMo-Megatron-Launcher.git
WORKDIR /workspace